DROP TABLE IF EXISTS Debt;
DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS
Debt(
  id SERIAL PRIMARY KEY NOT NULL,
  status BOOLEAN NOT NULL,
  title VARCHAR(256) NOT NULL,
  descr VARCHAR(256) NOT NULL,
  amount NUMERIC NOT NULL,
  createdBy INT NOT NULL,
  createdByName VARCHAR(256) NOT NULL,
  createdTo INT NOT NULL,
  createdToName VARCHAR(256) NOT NULL,
  creationDate VARCHAR(256) NOT NULL,
  dueDate VARCHAR(256) NOT NULL,
  completionDate VARCHAR(256)
);


CREATE TABLE IF NOT EXISTS
Users(
  id SERIAL PRIMARY KEY NOT NULL,
  UserName VARCHAR(256) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL UNIQUE,
  password VARCHAR(256) NOT NULL,
  phone VARCHAR(256) NOT NULL
);
