DROP TABLE IF EXISTS Debet;
DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS
Debet(
  id SERIAL PRIMARY KEY NOT NULL,
  status BOOLEAN NOT NULL,
  title VARCHAR(256) NOT NULL,
  descr VARCHAR(256) NOT NULL,
  amount NUMERIC NOT NULL,
  createdBy INT NOT NULL,
  createdTo INT NOT NULL,
  cteationDate TIMESTAMP NOT NULL,
  dueDate TIMESTAMP NOT NULL,
  completionDate TIMESTAMP NOT NULL
);


CREATE TABLE IF NOT EXISTS
Users(
  id SERIAL PRIMARY KEY NOT NULL,
  UserName VARCHAR(256) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL,
  phone VARCHAR(256) NOT NULL
);